# Generated by Django 2.2.22 on 2021-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
