# Generated by Django 2.2.22 on 2021-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210901_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
