# Generated by Django 2.2.22 on 2021-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210901_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
